services:
  app:
    container_name: auth_service_2
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    networks:
      - backend
    entrypoint: [ "sh", "/app/entrypoint.sh" ]

networks:
  backend:
    external: true
