"""+ WishlistItem and ViewedProduct

Revision ID: 3413a7394e3c
Revises: 8e03b18453e1
Create Date: 2025-01-24 01:11:32.302608

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3413a7394e3c"
down_revision: Union[str, None] = "8e03b18453e1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
