"""+ WishlistItem and ViewedProduct

Revision ID: 19201b9327b6
Revises: 3413a7394e3c
Create Date: 2025-01-24 01:13:09.888401

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "19201b9327b6"
down_revision: Union[str, None] = "3413a7394e3c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "viewedproducts",
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("client_uuid", sa.Uuid(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_viewedproducts_client_uuid"),
        "viewedproducts",
        ["client_uuid"],
        unique=False,
    )
    op.create_index(
        op.f("ix_viewedproducts_id"), "viewedproducts", ["id"], unique=True
    )
    op.create_index(
        op.f("ix_viewedproducts_user_id"),
        "viewedproducts",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "wishlistitems",
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("client_uuid", sa.Uuid(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_wishlistitems_client_uuid"),
        "wishlistitems",
        ["client_uuid"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wishlistitems_id"), "wishlistitems", ["id"], unique=True
    )
    op.create_index(
        op.f("ix_wishlistitems_user_id"),
        "wishlistitems",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_wishlistitems_user_id"), table_name="wishlistitems")
    op.drop_index(op.f("ix_wishlistitems_id"), table_name="wishlistitems")
    op.drop_index(
        op.f("ix_wishlistitems_client_uuid"), table_name="wishlistitems"
    )
    op.drop_table("wishlistitems")
    op.drop_index(
        op.f("ix_viewedproducts_user_id"), table_name="viewedproducts"
    )
    op.drop_index(op.f("ix_viewedproducts_id"), table_name="viewedproducts")
    op.drop_index(
        op.f("ix_viewedproducts_client_uuid"), table_name="viewedproducts"
    )
    op.drop_table("viewedproducts")
    # ### end Alembic commands ###
