"""add address models

Revision ID: 8e03b18453e1
Revises: a36caa6c0b1e
Create Date: 2025-01-21 11:08:24.819546

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8e03b18453e1"
down_revision: Union[str, None] = "a36caa6c0b1e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "useraddresss",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("street_line1", sa.String(), nullable=False),
        sa.Column("street_line2", sa.String(), nullable=True),
        sa.Column("city", sa.String(), nullable=False),
        sa.Column("state", sa.String(), nullable=True),
        sa.Column("phone", sa.String(), nullable=True),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_useraddresss_id"), "useraddresss", ["id"], unique=True
    )
    op.create_index(
        op.f("ix_useraddresss_user_id"),
        "useraddresss",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_useraddresss_user_id"), table_name="useraddresss")
    op.drop_index(op.f("ix_useraddresss_id"), table_name="useraddresss")
    op.drop_table("useraddresss")
    # ### end Alembic commands ###
